In [24]:
import json
import cv2
from PIL import Image, ImageDraw
import os

def pil_draw_rect(image, points):
    draw = ImageDraw.Draw(image)
    draw.rectangle(points, outline='red', width=3)
    return image

data_path = 'data_copy'

img_path = os.path.join(data_path,'15_X001_C016_1027_0.jpg')
with open(os.path.join(data_path, '15_X001_C016_1027_0.Json'), 'r', encoding='utf-8') as j_f:
    data = json.load(j_f)
x1 = int(data['Bounding'][0]['x1'])
y1 = int(data['Bounding'][0]['y1'])
x2 = int(data['Bounding'][0]['x2'])
y2 = int(data['Bounding'][0]['y2'])

img1 = Image.open(img_path)
bbox_img = pil_draw_rect(img1, [(x1, y1), (x2, y2)])
if not os.path.isdir('bbox_images'):
    os.mkdir('bbox_images')
bbox_img.save(os.path.join('bbox_images', 'pillow_15_X001_C016_1027_0.jpg'),'jpeg')


img2 = cv2.imread(img_path)
bbox_img2 = cv2.rectangle(img2, [x1,y1], [x2,y2], (255,0,0), 2)
cv2.imwrite(os.path.join('bbox_images', 'cv2_15_X001_C016_1027_0.jpg'), bbox_img2)
print(img2.shape, [x1,y1,x2,y2])


(1920, 1440, 3) [181, 375, 1487, 1438]


In [2]:
import os
import cv2
import data_preprocesmath.math.math.math.math.sing
import numpy as np
from PIL import Image


data_path = 'data'
files = set([x.split('.')[0] for x in os.listdir(data_path)])
for f in files:
    image_file = f + '.jpg'
    label_file = f + '.Json'
    # Pillow image -> OpenCV image
    img = Image.open(os.path.join(data_path, image_file))
    img = cv2.cvtColor(np.array(img), cv2.COLOR_BGR2RGB)
    # 이미지 데이터 resize
    resized_img = cv2.resize(img, dsize=(640, 640))
    cv2.imwrite(os.path.join('test_data', image_file), resized_img)
    # 라벨 데이터 전처리
    bbox_resized = data_preprocessing.resize_bbox(img, resized_img, os.path.join(data_path, image_file.split('.')[0]+'.json'))
    data_preprocessing.change_bbox(bbox_resized, os.path.join(data_path, image_file.split('.')[0]+'.json'), os.path.join('test_data', image_file.split('.')[0]+'.json'))

KeyError: 'x1'

In [55]:
img_original = Image.open(os.path.join('data_copy', '15_X001_C016_1027_0.jpg'))
img_resized = cv2.resize(img_original, dsize=(640,640))
with open(os.path.join('data_copy', '15_X001_C016_1027_0.json'), 'r', encoding='utf-8') as j_f:
    data = json.load(j_f)
x1 = int(data['Bounding'][0]['x1'])
y1 = int(data['Bounding'][0]['y1'])
x2 = int(data['Bounding'][0]['x2'])
y2 = int(data['Bounding'][0]['y2'])
img_resized = cv2.rectangle(img_resized, [x1,y1], [x2,y2], (255,0,0), 2)
cv2.imwrite(os.path.join('bbox_images','resized.jpg'), img_resized)
print(img_resized.shape)

error: OpenCV(4.8.0) :-1: error: (-5:Bad argument) in function 'resize'
> Overload resolution failed:
>  - src is not a numpy array, neither a scalar
>  - Expected Ptr<cv::UMat> for argument 'src'


In [54]:
from PIL import Image
import cv2
import numpy as np

image = os.path.join('data_copy', '15_X001_C016_1027_0.jpg')
img1 = Image.open(image)
img1.save(os.path.join('bbox_images', 'pillow.jpg'))

with open(os.path.join('data_copy', '15_X001_C016_1027_0.json'), 'r', encoding='utf-8') as j_f:
    data = json.load(j_f)
x1 = int(data['Bounding'][0]['x1'])
y1 = int(data['Bounding'][0]['y1'])
x2 = int(data['Bounding'][0]['x2'])
y2 = int(data['Bounding'][0]['y2'])

img2 = cv2.imread(os.path.join('bbox_images', 'pillow.jpg'))
bbox_img2 = cv2.rectangle(img2, [x1,y1], [x2,y2], (255,0,0), 2)
cv2.imwrite(os.path.join('bbox_images', 'cv2.jpg'), bbox_img2)


True

In [3]:
data_path = 'test_data'
# 데이터 전처리
json_files = [x for x in os.listdir(data_path) if x.split('.')[-1] in ('Json', 'json')]
image_files = [x for x in os.listdir(data_path) if x.split('.')[-1] in 'jpg']
for image_file in image_files:
    # # 라벨 데이터 백업 파일 저장
    # shutil.copy(os.path.join(data_path, image_file.split('.')[0]+'.json'), os.path.join(data_path, 'jsons', image_file.split('.')[0]+'.json'))
    # # 이미지 데이터 복사
    # shutil.copy(os.path.join(data_path, image_file), os.path.join(data_path, image_file.split('.')[0] + '_copy.jpg'))
    # 이미지 데이터 resize
    img = Image.open(os.path.join(data_path, image_file))
    img = cv2.cvtColor(np.array(img), cv2.COLOR_BGR2RGB)
    resized_img = cv2.resize(img, dsize=(640,640), interpolation=cv2.INTER_LINEAR)
    # 라벨 데이터 전처리
    bbox_resized = data_preprocessing.resize_bbox(img, resized_img, os.path.join(data_path, image_file.split('.')[0]+'.json'))
    data_preprocessing.change_bbox(bbox_resized, os.path.join(data_path, image_file.split('.')[0]+'.json'), os.path.join(data_path, image_file.split('.')[0]+'.json'))
    # # 라벨 데이터 제거
    # os.remove(os.path.join(data_path, image_file.split('.')[0]+'.json'))
    # 이미지 데이터 표준화
    normalized_image = data_preprocessing.normalize_image(resized_img)
    # 이미지 데이터 저장
    cv2.imwrite(os.path.join(data_path, image_file), resized_img)
    # # 원본데이터 imgs 폴더로 이동
    # shutil.move(os.path.join(data_path, image_file.split('.')[0] + '_copy.jpg'), os.path.join(data_path, 'imgs', image_file))

In [13]:
from collections import Counter
a = Counter(['1','1','2','3','3','4'])
b = [key for key,value in a.items() if value == 1]
print(b)

['2', '4']


In [19]:
import json
import cv2
import numpy as np
import os
import json
​
# 폴더 경로 설정
folder_path = "D:/sample"
​
# 결과를 저장할 폴더 경로 설정
save_dir = "D:/custom_results"
os.makedirs(save_dir, exist_ok=True)
​
# 모든 회전 각도 정의
all_angles = list(range(0, 361, 45))
​
# Get a list of all image files in the folder
image_files = [file for file in os.listdir(folder_path) if file.endswith(".jpg")]
​
def rotate_image(image, angle):
    h, w = image.shape[:2]
    cx, cy = w // 2, h // 2
    
    # 회전 변환 행렬 계산
    matrix = cv2.getRotationMatrix2D((cx, cy), angle, 1)
    
    # 회전시 이미지가 짤리지 않게 회전 후의 이미지 크기 계산
    abs_cos = abs(matrix[0, 0])
    abs_sin = abs(matrix[0, 1])
    new_w = int(h * abs_sin + w * abs_cos)
    new_h = int(h * abs_cos + w * abs_sin)
    
    # 변환 행렬 업데이트
    matrix[0, 2] += new_w / 2 - cx
    matrix[1, 2] += new_h / 2 - cy
​
    rotated_image = cv2.warpAffine(image, matrix, (new_w, new_h))
    
    return rotated_image
​
def update_json_data(data, angle, w, h):
    # JSON 데이터에서 바운딩 박스 정보 가져오기
    bounding_boxes = data["Bounding"]
    
    for box in bounding_boxes:
        x1, y1, x2, y2 = float(box["x1"]), float(box["y1"]), float(box["x2"]), float(box["y2"])
        
        # 회전 중심점 계산
        cx, cy = w // 2, h // 2
        
        # 각도에 따라 바운딩 박스 좌표 계산
        radians = np.radians(angle)
        cos_theta = np.cos(radians)
        sin_theta = np.sin(radians)
        
        # 각도에 따라 좌표 회전
        new_x1 = (x1 - cx) * cos_theta - (y1 - cy) * sin_theta + cx
        new_y1 = (x1 - cx) * sin_theta + (y1 - cy) * cos_theta + cy
        new_x2 = (x2 - cx) * cos_theta - (y2 - cy) * sin_theta + cx
        new_y2 = (x2 - cx) * sin_theta + (y2 - cy) * cos_theta + cy
        
        # 업데이트된 바운딩 박스 정보를 JSON 데이터에 저장
        box["x1"], box["y1"], box["x2"], box["y2"] = str(new_x1), str(new_y1), str(new_x2), str(new_y2)
​
# 이미지와 해당하는 .json 파일에 대하여 작업 수행
for image_file in image_files:
    # Extract the filename without extension
    filename, _ = os.path.splitext(image_file)
​
    # Construct the full paths for the image and JSON file
    image_path = os.path.join(folder_path, image_file)
    json_file = filename + ".json"
    json_path = os.path.join(folder_path, json_file)
​
    # Load the image and JSON data
    image = cv2.imread(image_path)
    image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
​
    with open(json_path, 'r', encoding='utf-8') as f:
        data = json.load(f)
​
    # 0도부터 360도까지 45도 간격으로 이미지 회전
    for angle in all_angles:
        rotated_image = rotate_image(image, angle)
        rotated_image_path = os.path.join(save_dir, f'{filename}_rotated_{angle}.jpg')
​
        # Save the rotated image
        cv2.imwrite(rotated_image_path, rotated_image)
​
        # Update JSON data for the rotated image
        update_json_data(data, angle, image.shape[1], image.shape[0])
        rotated_json_path = os.path.join(save_dir, f'{filename}_rotated_{angle}.json')
        with open(rotated_json_path, 'w', encoding='utf-8') as json_file:
            json.dump(data, json_file)
​
print('Done')

[[ 1.  0.  0.]
 [-0.  1.  0.]]
[[ 7.07106781e-01  7.07106781e-01 -1.00660172e+02]
 [-7.07106781e-01  7.07106781e-01  8.36984848e+02]]
[[ 6.123234e-17  1.000000e+00  4.200000e+02]
 [-1.000000e+00  6.123234e-17  1.500000e+03]]
[[-7.07106781e-01  7.07106781e-01  1.25698485e+03]
 [-7.07106781e-01 -7.07106781e-01  1.60066017e+03]]
[[-1.0000000e+00  1.2246468e-16  1.9200000e+03]
 [-1.2246468e-16 -1.0000000e+00  1.0800000e+03]]
[[-7.07106781e-01 -7.07106781e-01  2.02066017e+03]
 [ 7.07106781e-01 -7.07106781e-01  2.43015152e+02]]
[[-1.8369702e-16 -1.0000000e+00  1.5000000e+03]
 [ 1.0000000e+00 -1.8369702e-16 -4.2000000e+02]]
[[   0.70710678   -0.70710678  663.0151519 ]
 [   0.70710678    0.70710678 -520.66017178]]
[[ 1.  0.  0.]
 [-0.  1.  0.]]
[[ 7.07106781e-01  7.07106781e-01 -1.00660172e+02]
 [-7.07106781e-01  7.07106781e-01  8.36984848e+02]]
[[ 6.123234e-17  1.000000e+00  4.200000e+02]
 [-1.000000e+00  6.123234e-17  1.500000e+03]]
[[-7.07106781e-01  7.07106781e-01  1.25698485e+03]
 [-7.071

In [1]:
import torch

USE_CUDA = torch.cuda.is_available()
print(USE_CUDA)

True


In [ ]:
# assuming box coords = [x_min, y_min, x_max, y_max]
def cropBoxByPercentage(box_coords, image_width, image_height, x_percentage=0.05, y_percentage=0.05):
    box_xmin = box_coords[0]
    box_ymin = box_coords[1]
    box_xmax = box_coords[2]
    box_ymax = box_coords[3]
    box_width = box_xmax-box_xmin+1
    box_height = box_ymax-box_ymin+1
    dx = int(x_percentage * box_width)
    dy = int(y_percentage * box_height)
    box_xmin = max(0, box_xmin-dx)
    box_xmax = min(image_width-1, box_xmax+dx)
    box_ymin = max(0, box_ymax - dy)
    box_ymax = min(image_height - 1, box_ymax + dy)
    return np.array([box_xmin, box_xmax, box_ymin, box_ymax])

In [10]:
import math
width = 1511
height = 428
angle = 45
center_x = 755.5
center_y = 646

half_width = width / 2
half_height = height / 2
angle_rad = angle * (math.pi / 180)
offset_x1 = half_width * math.cos(angle_rad) - half_height * math.sin(angle_rad)
offset_y1 = half_width * math.sin(angle_rad) + half_height * math.cos(angle_rad)

offset_x2 = -half_width * math.cos(angle_rad) - half_height * math.sin(angle_rad)
offset_y2 = -half_width * math.sin(angle_rad) + half_height * math.cos(angle_rad)

offset_x3 = -half_width * math.cos(angle_rad) + half_height * math.sin(angle_rad)
offset_y3 = -half_width * math.sin(angle_rad) - half_height * math.cos(angle_rad)

offset_x4 = half_width * math.cos(angle_rad) + half_height * math.sin(angle_rad)
offset_y4 = half_width * math.sin(angle_rad) - half_height * math.cos(angle_rad)


rotated_x1 = center_x + offset_x1
rotated_y1 = center_y + offset_y1

rotated_x2 = center_x + offset_x2
rotated_y2 = center_y + offset_y2

rotated_x3 = center_x + offset_x3
rotated_y3 = center_y + offset_y3

rotated_x4 = center_x + offset_x4
rotated_y4 = center_y + offset_y4


382.89832201251556 685.5400243603578
-685.5400243603578 -382.89832201251556
-382.89832201251556 -685.5400243603578
685.5400243603578 382.89832201251556


In [11]:
print(rotated_x1, rotated_y1)
print(rotated_x2, rotated_y2)
print(rotated_x3, rotated_y3)
print(rotated_x4, rotated_y4)

1138.3983220125156 1331.5400243603578
69.95997563964215 263.10167798748444
372.60167798748444 -39.54002436035785
1441.0400243603578 1028.8983220125156


In [6]:
import time
import os
import shutil
from tqdm import tqdm

def heavy_work():
    shutil.copy(os.path.join('backup', f), os.path.join('backup2',f))


if __name__ == '__main__':
    import multiprocessing
    files = [x for x in os.listdir('backup')]
    start = time.time()
    procs = []
    for f in tqdm(files):
        p = multiprocessing.Process(target=heavy_work, args=(f, ))
        p.start()
        procs.append(p)

    for p in procs:
        p.join()  # 프로세스가 모두 종료될 때까지 대기

    end = time.time()

    print("수행시간: %f 초" % (end - start))    

100%|██████████| 21144/21144 [06:02<00:00, 58.36it/s] 


수행시간: 362.789462 초


In [5]:
import time
import os
import shutil
from tqdm import tqdm

def heavy_work():
    files = [x for x in os.listdir('backup')]
    for f in tqdm(files):
        shutil.copy(os.path.join('backup', f), os.path.join('backup2',f))


start = time.time()

heavy_work()

end = time.time()

print("수행시간: %f 초" % (end - start))

  0%|          | 0/21144 [00:00<?, ?it/s]

100%|██████████| 21144/21144 [03:49<00:00, 92.26it/s] 

수행시간: 229.201456 초


In [12]:
import multiprocessing

def process_item(item):
    # Do some processing on the item
    result = item * 2
    return result

if __name__ == '__main__':
    items = [1, 2, 3, 4, 5]
    num_processes = 3

    with multiprocessing.Pool(processes=num_processes) as pool:
        results = pool.map(process_item, items)

    print('Processed results:', results)

In [1]:
import multiprocessing

def process_function(argument):
    result = argument * 2
    return result

if __name__ == '__main__':
    argument = 42
    num_processes = 4

    with multiprocessing.Pool(processes=num_processes) as pool:
        results = pool.map(process_function, [argument] * num_processes)
        pool.close()
        pool.join()

    print('Processed results:', results)

In [3]:
# SuperFastPython.com
# example of running a function in a new process
from multiprocessing import Process
 
# a task to execute in another process
def task():
    print('This is another process', flush=True)
 
# entry point for the program
if __name__ == '__main__':
    # define a task to run in a new process
    p = Process(target=task())
    # start the task in a new process
    p.start()
    # wait for the task to complete
    p.join()

This is another process
